<<<<<<< HEAD
=======
[build]
<<<<<<< HEAD
  base = "frontend"
  command = "npm run build"
  publish = "frontend/dist"
=======
  command = "npm run build"
  publish = "dist"
>>>>>>> 685137abb47f4a3ebd0df6531f49d7d2080d8058

>>>>>>> ebcec9630b5c1142cd921b58551be1bac1c32579
[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API proxy for local development
[[redirects]]
  from = "/api/*"
  to = "https://dwansys.onrender.com/api/:splat"
  status = 200
  force = true
=======
  force = true
>>>>>>> 685137abb47f4a3ebd0df6531f49d7d2080d8058
