services:
  - type: web
    name: dwansys-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: LOG_LEVEL
        value: info
      - key: CORS_ORIGIN
        value: https://dwansys.com,https://www.dwansys.com,https://dwansyss.netlify.app
      - key: SUPABASE_URL
        value: your_supabase_project_url
      - key: SUPABASE_KEY
        value: your_supabase_anon_key
      - key: SUPABASE_SERVICE_KEY
        value: your_supabase_service_role_key
      - key: EMAIL_HOST
        value: your_smtp_host
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USER
        value: your_email_username
      - key: EMAIL_PASS
        value: your_email_password
      - key: EMAIL_FROM
        value: noreply@yourdomain.com